### ISSUE TITLE
Add support for PL1 projects and the SRDC cluster

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#132]
In the future, support for the SRDC cluster may be required. Additional security measures would need to be taken into consideration.

**Comment by matthew-li** [comment]
Notes from today's meeting:
- These directories are requested within the context of an existing project.
- Project managers should be able to specify a subset of users that have access to the directories.
- Question: Can a single project request more than one secure directory?

**Comment by wfeinstein** [comment]
@matthew-li 
Let's stick with one FC_xxx with one secure directory

**Comment by matthew-li** [comment]
From today's meeting:
- The allowance used should correspond to an existing project (i.e., `fc_project` or `ac_project`), passed as the `--account` argument during job submission. (This requires confirmation.)
- Each user added to the secure subset of users is granted a secure home directory and a secure scratch directory.
- Users may not request to join the secure subset; additions must be initiated by the PI.

**Comment by wfeinstein** [comment]
-bash-4.2# ls /global/scratch2/pl1data/ 
alanaw1        calvin_chiu  gillichu	    m_chintalapati  mughal	prakruthi_burra  rtournebize   zhangyulin9806
almahalgren    cwhaley	    isabel_serrano  meaghan_marohn  natecramer	psudmant	 shenghuanjie
annabel_large  gbrooks	    kailey_ferger   moorjani	    nilah	rrp2016		 weiwang2020

-bash-4.2# ls -l /global/home/groups/pl1data/
total 24
drwxrws--- 1 root pl1_bcht     104 Feb  4  2020 pl1_bcht
drwxrws--- 1 root pl1_grail     80 Feb  4  2020 pl1_grail
drwxrws--- 1 root pl1_moorjani 164 Mar 20  2020 pl1_moorjani
drwxrws--- 1 root pl1_nilab    156 Feb 28  2020 pl1_nilab
drwxrws--- 1 root pl1_respect   84 Oct 19  2020 pl1_respect
drwxrws--- 1 root pl1_riddell    0 Oct  6  2019 pl1_riddell
drwxrws--- 1 root pl1_sudmant  616 Sep  3  2019 pl1_sudmant

PL2 projects get space under /global/scratch2/pl1data/ and /global/home/groups/pl1data/
There won't be new allocations for job submissions, the difference I think is where users store data and submit jobs with PL2 data.

**Comment by wfeinstein** [comment]
@matthew-li 
I think we can safely assume there is only one PL2 project associated with an existing fc_xxx project.

**Comment by matthew-li** [comment]
From today's meeting:
- PIs/Managers should have access to a form that allows them to request a secure directory on the cluster, or, separately, access to the SRDC cluster.
    - Secure Directory
        - Administrators would approve/deny a request based on some criteria (@wfeinstein will clarify what those are). Then the directories would be created.
        - PIs/Managers could then grant users access to this directory. The addable users are not limited to the users on the project, since PIs/Managers could have multiple projects (i.e., `fc_project` and `ac_project`), and it would be shared amongst them.
    - SRDC
        - The primary blocker for tracking Service Units usage is installing the Slurm plugins on the cluster.

**Comment by matthew-li** [comment]
@wfeinstein Would there _ever_ be a case where a PI would like to add a user to the `/global/home/groups/pl1data/{project_name}/` directory, but not the `/global/scratch2/pl1data/{project_name}/` directory?

**Comment by wfeinstein** [comment]
@matthew-li 
Both scratch2 and groups/pl1data/{project_name}/ are created once the PI is approved

**Comment by wfeinstein** [comment]
@matthew-li 
SRDC has its own slurm db running. Plugins will not be implemented for now within myBRC, but should allow splitting SUs from Savio to SRDC with the option of %SUs being transferred to SRDC. The rest be managed separately on SRDC separately.

**Comment by matthew-li** [comment]
@wfeinstein Are there (or will there be) secure directories on LRC, or is this a BRC-only feature?

**Comment by matthew-li** [comment]
For splitting some number of SUs to SRDC, running the command `add_service_units_to_project` (with a negative input and a descriptive reason) may be sufficient for now.

**Comment by matthew-li** [comment]
The following need to be imported:
- A list of existing directories, and which projects they are under:
- For each directory, a list of users with access to that directory.

**Comment by matthew-li** [comment]
I mistakenly thought that a user scratch directory would be located at `/path/to/scratch/{project_name}/{username}/`, but it is actually located at `/path/to/scratch/{username}/`.

Though the code changes can be safely deployed, actual `Allocations` and `AllocationUsers` for existing directories should not be created until the associated path-creation logic is fixed.

Moreover, a user may (unlikely) have access to a scratch directory under multiple `Allocations`. The user's directory should not be deleted if this is the case. @jofeinstein We'll want to account for this somehow, just in case.

**Comment by matthew-li** [comment]
From yesterday's meeting:
- The admin checklist includes:
    1. Confirm that the research group has consulted with Research Data Management (RDM).
    2. Confirm that the Memorandum of Understanding has been signed.
    3. Perform directory setup on the cluster.
- #399 would be a useful future optimization for step 2, so that an admin does not need to separately generate the MOU, send it to the user, and await a response.
