### ISSUE TITLE
Allow PIs to be exempt from notification emails; shift emails to Managers

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#14]
Currently, PIs cannot avoid receiving notification emails.

In our service, POCs ("Manager" roles) perform tasks on behalf of PIs, so they should be the primary recipients of emails.

PIs should receive emails by default. If they don't want to receive emails, they should create a ColdFront account and update their email preferences.

**Comment by matthew-li** [comment]
For context, this [line](https://github.com/ucb-rit/coldfront/blob/develop/coldfront/core/project/templates/project/project_detail.html#L155) is what I was referring to.

As part of #13, the "Principal Investigator" `ProjectUserRoleChoice` was added, but a similar check for this role was not added to the template above. This turns out to be what we want (i.e., PIs can disable emails, but Managers cannot).

But I think we should add the additional caveat that PIs can disable emails iff there is at least one other "Manager" or "Principal Investigator" on the `Project` with emails enabled. @kmuriki Does this sound reasonable?

**Comment by matthew-li** [comment]
@ViRu-ThE-ViRuS We've made some workflow changes in the last week, removing the "Enable Notifications" checkboxes from the Project Detail view.

Can you double check if PIs are allowed to update their notifications from `/project/{id}/user-detail/{id}`? The logic should be the same: PIs can disable when managers exist, managers cannot disable, when the last manager leaves, all PIs have their notifications enabled again.

Another caveat is that regular users should have their notifications disabled by default. @kmuriki Do we want to completely disallow regular users from changing this setting? (It seems like the emails being sent are only really relevant to managers/PIs.)

**Comment by kmuriki** [comment]
Yes thats right. Most communication from the system will be to the PIs and/or managers.

**Comment by ViRu-ThE-ViRuS** [comment]
@matthew-li sounds good, ill patch this up!
