### ISSUE TITLE
confusing screen for adding new users to a project

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#173]
**This issue was moved here from the ucb-rit/mybrc repo.**

I clicked on "Add Users" for my fc_paciorek account. I got the screen shown attached.

It's not clear to me what I should be clicking:

1. The 'select all' is shown very similarly to 'savio compute' so it wasn't obvious that 'savio compute' is one element and 'select all' is to select all elements when there is more than one. Most people will probably only see 'savio compute'. Do we really need 'select all'?
2. Given fc_paciorek is a Savio project, why do I even need to select 'savio_compute'?
3. There is no checkbox next to the "James Duncan" line, only in the line just above. So it's not clear what I should be selecting to add this user.
4. I clicked on what I could but I don't seem to be able to add James. He doesn't show up as a pending user.

**Comment by matthew-li** [comment]
@paciorek Thanks for raising this.

1-2. There are some database models that we've mostly abstracted away, except for here. You're right that users being added to this project should be added to the Savio allocation automatically. Here's what it looks like without this section:

![greyed](https://user-images.githubusercontent.com/10734545/119384014-efc9a880-bc78-11eb-9fd7-870e40af613f.png)

3-4. Given the change above, the help text should be closer now: "You may only add users who have signed the access agreement." A more explicit rewording might be: "Users who have not signed the access agreement are grayed out and cannot be selected until they do so."

**Comment by paciorek** [comment]
I just tried it again and it looks better. You still might add a clarifying note like this:

"You may only add users who have signed the access agreement (no check box will appear below for those who have not signed)."
