### ISSUE TITLE
Load ABC users into the database

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#176]
Currently, there is support for new requests to get access to the `ABC` cluster (namely, by joining the `abc` project).

Existing users with access to this cluster should be loaded into the database.

**Comment by kmuriki** [comment]
@matthew-li Look at https://docs.google.com/spreadsheets/d/1zvTLSbUNtoBoSQcMCdOlJTm8OvvwWnlfP2_0gQLibR8/edit#gid=516157066 and the tab ABC-users-May-25-2021
