### ISSUE TITLE
add a bit more explanatory text in the email when a user is added to a project

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/coldfront#181]
I was added to a project (without requesting it) and got this text in the email:

"The managers of Project ac_exoplanet have added you to their project. A request for cluster access under this project has been generated."

Also, mybrc shows I don't have access to the project yet.

Perhaps the "A request for cluster access under this project has been generated" could more clearly indicate that while the project managers have given permission, that this is waiting on actually configuring things on the system. Maybe:

"The managers of Project ac_exoplanet have added you to their project. A request for cluster access under this project has been generated and sent to the cluster administrators. Once access is set up, you will receive a message indicating that you can run jobs under this project."

**Comment by matthew-li** [comment]
Thanks, I've incorporated the new text.
