### ISSUE TITLE
how give more info to users who have created a brc portal account but do not have a cluster account

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/coldfront#184]
Under my paciorek@b.e portal account (which is at this point basically a dummy portal account), it shows: No Cluster Account in a red button next to "Your BRC Supercluster account username".  Should we add some help text indicating if setting up a cluster account is in progress, or why they don't have an account and/or indicate how they get an account? I think it may be confusing to users just to see they don't have a cluster account with no further info.

I guess the basic answer is that a cluster account is only created after a user has been added to at least one project and access has been granted to that project by the adminstrators. If that's how things work, we should probably indicate that to the user.

**Comment by paciorek** [comment]
Related to this, in our current Savio docs, we have a whole section talking about how to get a user account. In the portal, there is not really a direct/clear way to 'get an account'. Rather the portal gives the tasks as 1) signing the agreement and 2) joining a project. So in the docs we'll also have to make the wording clear in terms of what 'getting an account' means in the context of the portal.

**Comment by markyashar** [comment]
Good point. I can add a sentence or two in the documentation something like: "If a researcher does not already have a BRC cluster account, one will be created for them when they submit a request to join a project for the first time or when a PI adds them to a project..."

**Comment by kmuriki** [comment]
Yes the structure has slightly changed now. Getting cluster account is an inherent feature now of joining the project. As listed on the welcome page we want users to (1) sign user agreement and (2) join a project which will grant them a cluster account if that doesn't exist. I dunt want to load the home page with a lot of text and make it very busy. I think the current page with status fields given enough feedback to the users.

**Comment by paciorek** [comment]
I'm fine with leaving the portal as is as long as the docs are clear, but I think there could still be some more clarity there. I'll comment on that in the merge request in gitlab.
