### ISSUE TITLE
Initial email sent when user requests creation of accoumt

### ISSUE THREAD

**Issue by markyashar** [ucb-rit/coldfront#199]
When a user requests a cluster account to be created for them through the MyBRC portal (i.e., when they request to join a cluster project for the first time), it may be worthwhile to consider whether the initial confirmation email(s) that is sent to the user should include some material on the need for the user to make sure they familiarize themselves with the Savio documentation and training materials as they wait for their account to be processed and *before* they start using Savio for the first time. Perhaps the initial confirmation email sent to a new/prospective user could include something like this (this may be a bit long, so a shortened or summarized version of this could be considered as well):

"As you wait for your account to be processed and to get access to Savio, we strongly recommend, as we do with all new Savio users,  that you see and familiarize yourself with our extensive Savio documentation here:

https://docs-research-it.berkeley.edu/services/high-performance-computing/

As you begin working on the Savio system, a lot of the questions that may come up are answered in the documentation.

A good place to start (if you haven't already done so) would be to carefully read through our documentation on Getting An Account on Savio:

https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-account/

as well as Frequently Asked Questions:

https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/frequently-asked-questions

Also, please take the time if at all possible to see the training materials at https://htmlpreview.github.io/?https://github.com/ucb-rit/savio-training-intro-spring-2021/blob/master/intro_slides.html from a recent Intro to Savio Training Workshop, as well as https://github.com/ucb-rit/savio-training-slurm-2020/blob/main/slurm.md from a recent Savio SLURM training workshop.

- A partial set of videos covering some of that intro material in various trainings can also be found at
https://www.youtube.com/watch?v=Denj8NyUPVo&list=PLinUqTXTvciPNjqPxvScsXVLLh5MLCz4P

- Also, our consultants have done a lot of user facing trainings in the past and many of those sessions are video/audio recorded and available for users to consume here as well:

https://research-it.berkeley.edu/services/high-performance-computing/training-and-tutorials

Thank you

....."

**Comment by matthew-li** [comment]
Closed by #219.
