### ISSUE TITLE
Remove unnecessary models and features

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#2]
Features that may be unneeded include: `Publication`, `Grant`, `ResearchOutput`, etc.

The models and referencing code should be commented out so that they could potentially be restored if needed.

**Comment by matthew-li** [comment]
A model diagram can be generated with the following:

```
# Install graphviz (via brew, yum, etc.).
pip install pygraphviz
pip install django-extensions
# Add django_extensions to INSTALLED_APPS in settings.py.
python manage.py graph_models -a -o models.png
```

**Comment by matthew-li** [comment]
We should consider whether or not to keep `HistoricalRecords` on a model-by-model basis. They're more important for the accounting-related models. We'll want to track changes to allocation values, for example.

**Comment by ViRu-ThE-ViRuS** [comment]
module cleanup is complete, will take up further cleanup on model-by-model basis. Need further discussion.
