### ISSUE TITLE
Allow select users to view all users

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#201]
A subset of users (e.g., consultants) should have the ability to view all users.

The "User Search" in the "Staff" dropdown menu is available to staff users, so the desired users can be given `is_staff` status. However, this does not show a list of all users.

A view for listing all users, analogous to "All Projects" for superusers, would need to be built, then made available to staff and superusers.

**Comment by ViRu-ThE-ViRuS** [comment]
closing here
