### ISSUE TITLE
Allow table of new project requests to be sorted

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#206]
It would be helpful to be able to sort the table of new project requests on arbitrary fields (e.g., date, allocation type, status).

The code for sorting projects on other views can be adapted for this purpose.

**Comment by ViRu-ThE-ViRuS** [comment]
@matthew-li I can handle this!

**Comment by matthew-li** [comment]
Please do, thanks!

**Comment by matthew-li** [comment]
From today's dev check-in:
- The fields to add sorting to are: "#", "Date Requested/Last Modified", "Requester Email", "Project", "Allocation Type", and "PI". The "Pooling?" and "Status" fields can be ignored.
- The same logic should be implemented for both Savio and Vector requests.
- A good reference for this functionality is `ProjectListView`.

**Comment by matthew-li** [comment]
@Leon-Goldner-Cohen-Tzedek On the initial load, the entries should appear in ascending ID order.
