### ISSUE TITLE
Add an "Are you sure" popup when denying cluster account requests

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#207]
Currently, these requests are denied by a single click, without any confirmation. Add a popup that requests confirmation from the user before proceeding.

**Comment by ViRu-ThE-ViRuS** [comment]
@matthew-li mind if I handle this?

**Comment by matthew-li** [comment]
Go for it, thanks!

**Comment by ViRu-ThE-ViRuS** [comment]
closing here
