### ISSUE TITLE
Changing/Updating BRC Cluster username via MyBRC Portal?

### ISSUE THREAD

**Issue by markyashar** [ucb-rit/coldfront#215]
In the ServiceNow Incident ticket INC1236229 the user asks whether it is possible for them to make a request to change their BRC Cluster username via the MyBRC Portal. It might be worthwhile to consider adding a feature in the portal (maybe under the "user profile" section) that enables users to make requests to change/edit or update their cluster usernames (as long as they are unique and follow the rules for acceptable usernames)?

**Comment by matthew-li** [comment]
I don't believe we currently support changing usernames on the cluster itself, so I'm closing this for now, although we could revisit it in the future.
