### ISSUE TITLE
Prevent users from making many PI requests

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#22]
Currently, whenever a user requests to become a PI, an email is sent to admins. There is no check to prevent multiple requests, so many repeated emails could be sent.

**Comment by matthew-li** [comment]
This might be done with a new `PIRequest` model, or with some extra state stored elsewhere. If a user has already made a request, the appropriate message should be displayed.

**Comment by ViRu-ThE-ViRuS** [comment]
Closing Here!
