### ISSUE TITLE
Integrate intermediate spreadsheet for new cluster accounts into portal

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#239]
Below is the current workflow for handling new cluster account requests.
1. A new request is created.
2. An admin sets its status to "Processing" via the UI and copies information about it into a spreadsheet.
3. A script on the cluster, running in a cron job, checks for new entries in this spreadsheet, and performs the necessary setup on the cluster.
4. An admin manually checks that the setup is complete, removes the entry from the spreadsheet, and marks the request as complete in the portal.
5. The user is notified that their account is ready.

This spreadsheet is an additional source of truth, which should be eliminated. At a high level:
- The scripts on the cluster should instead fetch any requests marked as "Processing" directly from the portal, and process them.
- New REST API endpoints should be added to support this.
- The admin still needs to verify that setup was successful before marking the request as complete in the portal.

Additional details (i.e., what if the script runs on the same request twice?) need to be fleshed out.

**Comment by kmuriki** [comment]
I would not call this intermediate spreadsheet holding the current queue of accounts to be setup as a "source of truth". It no where any source of any kind of truth. 

Yes it will be nice to get rid of this spreadsheet in the workflow but also there are concerns raised by others in automating the workflow. Just make sure enough eyes are looking at the queue and validating and vetting the requests and random people are not able to get cluster accounts easily without proper verification.

**Comment by matthew-li** [comment]
@kmuriki Thanks for the feedback. "Source of truth" is probably not the right phrase, but it is additional state that could be queried directly from the portal.

I can envision having the cluster scripts only process requests that are X hours old, to add some delay.

**Comment by kmuriki** [comment]
Yep additional step/state is right term. 

Not sure if just delaying the automatic process is sufficient. May be we need to mandate another review step. Mark already does one level of review and then there got to be HPCS team member review step in the portal workflow itself but again just discuss internally and decide what is best. Hope this helps.

**Comment by matthew-li** [comment]
This will be resolved as part of #337.
