### ISSUE TITLE
Change "Pending Join Requests" to "Join Requests Pending Approval"

### ISSUE THREAD

**Issue by jpdunc23** [ucb-rit/coldfront#260]
A user came to office hours confused because they received a "Request to Join Approved" email on the morning of Tuesday Sept 14, at which point on the "Join a Project" page of the MyBRC portal the project was removed from the "Pending Join Requests" section. They had the impression that the estimated time shown next to the project in "Pending Join Requests" was the estimate for gaining access to the project on the cluster, and became worried that the request had failed.

Changing the language from "Pending Join Requests" to "Join Requests Pending Approval" should make the purpose of that section more clear.

**Comment by matthew-li** [comment]
@jpdunc23 Thanks for raising this. I've addressed this in #261, with relevant clarifying text at this [line](https://github.com/ucb-rit/coldfront/pull/261/files#diff-38c7a2fcf568edacb89a3612e7c7900a7c8125072b3513313fd338196f9d70a0R17).

I'm closing this for now, but let me know if this can be clarified further.

(This will be deployed Monday morning.)

**Comment by jpdunc23** [comment]
Thank you!
