### ISSUE TITLE
Suggesiton for small modificaiton to introductory email sent to users when they first request an account

### ISSUE THREAD

**Issue by markyashar** [ucb-rit/coldfront#280]
Below is a suggestion to consider for the email to send to users when they first request a user account via the MyBRC Portal. It is the same as the message that is currently used except there is an update for the latest Intro to Savio training 
session for Fall 2021,

https://github.com/ucb-rit/savio-training-intro-fall-2021
 
https://htmlpreview.github.io/?https://github.com/ucb-rit/savio-training-intro-fall-2021/blob/main/intro.html

and a couple of additional sentences have been included, i.e.,

"We update the Savio documentation on a regular basis, so we encourage users to check back and consult the documentation frequently and often for additions and new content.
 
Moreover, if you have suggestions for content to be added/included in our Savio documentation, please let us know.
 
We also encourage Savio users to communicate and work with other Savio users in their labs or elsewhere when troubleshooting and debugging issues come up, as some of you are collaborating on the same projects and using the same software and software libraries, using the same or similar scripts, sharing the same data, etc."

Here is a suggestion for the slightly modified message in its entirety:

"Dear X,

Your request to join Project XX has been approved by its managers. A request to get access to the project on the cluster has been generated, and will be processed by admins.

As you wait for your account to be processed and to get access to Savio,, we strongly recommend that you see and familiarize yourself with our extensive Savio documentation here:
 
https://docs-research-it.berkeley.edu/services/high-performance-computing/
 
As you begin working on the Savio system, a lot of the questions that may come up are answered in the documentation.
 
A good place to start (if you haven't already done so) would be to carefully read through our documentation on Getting An Account on Savio:
 
https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-account/
 
and How To Get Help on Savio:
 
https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/
 
https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/good-help-requests/
 
as well as Frequently Asked Questions:
 
https://docs-research-it.berkeley.edu/services/high-performance-computing/getting-help/frequently-asked-questions
 
We update the Savio documentation on a regular basis, so we encourage users to check back and consult the documentation frequently and often for additions and new content.
 
Moreover, if you have suggestions for content to be added/included in our Savio documentation, please let us know.
 
We also encourage Savio users to communicate and work with other Savio users in their labs or elsewhere when troubleshooting and debugging issues come up, as some of you are collaborating on the same projects and using the same software and software libraries, using the same or similar scripts, sharing the same data, etc.
 
Also, please take the time if at all possible to see the training materials at
 
https://github.com/ucb-rit/savio-training-intro-fall-2021
 
https://htmlpreview.github.io/?https://github.com/ucb-rit/savio-training-intro-fall-2021/blob/main/intro.html
 
from a recent Intro to Savio Training Workshop, as well as
 
https://github.com/ucb-rit/savio-training-slurm-2020/blob/main/slurm.md
 
from a recent Savio SLURM training workshop.
 
A partial set of videos covering some of that intro material in various trainings can also be found at
 
https://www.youtube.com/watch?v=Denj8NyUPVo&list=PLinUqTXTvciPNjqPxvScsXVLLh5MLCz4P
 
Also, our consultants have done a lot of user facing trainings in the past and many of those sessions are video/audio recorded and available for users to consume here as well:
 
https://research-it.berkeley.edu/services/high-performance-computing/training-and-tutorials
 
If you have any further questions, please contact us at
brc-hpc-help@berkeley.edu.

Thank you,

MyBRC User Portal team
https://mybrc.brc.berkeley.edu
Email : brc-hpc-help@berkeley.edu"

**Comment by matthew-li** [comment]
Thanks @markyashar. We will incorporate this into the next release.
