### ISSUE TITLE
Add List/Detail Views for Jobs

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#320]
Implement a List view for displaying a list of `Jobs` and a Detail view for displaying the contents of a particular `Job`.

**List View (`/jobs/`)**
- Add filtering by date (i.e., submitted since, completed before, started since, etc.).
    - A date-picker widget would be useful for these.
- Add filtering by cost (i.e., greater than, less than, etc.).
- Add filtering by partition, username, project name, status, etc.

**Detail View (`/jobs/{jobslurmid}/`)**
- Display a table of the job's values.

**Permissions (subject to change)**
- Users may view jobs submitted under projects of which they are a member.
- Staff and superusers may view all jobs.

**Miscellanea**
- Use different colors for different job statuses, which can include "running", "completing", etc.
    - "Completing" is stored in the database because that is the value sent by the Slurm plugins, but this should be displayed as "Completed" or "Complete".
- Dates are stored in UTC, but users will expect to be interacting with LA time dates.
- Projects may have many jobs; consider any performance implications.
    - For instance, sorting could incur a high cost.

**Comment by matthew-li** [comment]
`bootstrap/development/load_database_backup.sh` explicitly avoids loading `Jobs`, but could be modified to do so.

Warning: I haven't tried this, and it could take an hour or more. `pg_restore` has a `--number-of-jobs` flag that could speed this up.

**Comment by matthew-li** [comment]
Also, register the default views for this model in the Django admin interface. (You could make a separate PR for this, no testing necessary.)

**Comment by wfeinstein** [comment]
@matthew-li @jofeinstein 
Can we add a function to allow admins to download the queried job list?  So that I can parse the job data to collect some metrics.

**Comment by wfeinstein** [comment]
@matthew-li  
Yes, a button for export would work. Essentially this belongs to the DB query category.
