### ISSUE TITLE
Stand up API endpoints for processing requests

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#337]
Currently, cluster scripts are updating cluster account requests and pending removal requests by simulating logging in, navigating to the requisite pages, submitting forms, etc.

Create API endpoints so that updates may be done directly, as with identity linking requests.

**Comment by matthew-li** [comment]
@jofeinstein Can you work on this issue?

We'll need endpoints for:
(a) Cluster access requests
(b) Project user removal requests

For each, we'll want a way to `GET` requests, filtering by status name, as well as `PATCH` the status of a request.

When a request goes from the processing state to the complete one, we need to run some handling (e.g., for (b), run `ProjectRemovalRequestRunner`.). We should refactor as much of the logic in the existing UI views as possible for reuse. You'll want to define a custom `patch` method in the view set, where this logic would go.

As a start, you can handle (b). After that, for (a), we may want to create a new `ClusterAccessRequest` model first. (a) will also be slightly different for BRC vs. LRC (e.g., LRC also has Project IDs, host users).

You can pattern match against `IdentityLinkingRequestViewSet` and other endpoints to get you 90% of the way. For that endpoint, I also wrote some sample client code (to be used on the cluster) which I can send you.

**Comment by matthew-li** [comment]
After #332, there will also be a need for an endpoint for processing cluster account deletion requests.

**Comment by matthew-li** [comment]
@jofeinstein I ran into an edge case:
- A user is added to a project.
- A `ClusterAccessRequest` (`R`) is generated.
- The user is removed from the project.
- `R` lingers.

Attempting to complete `R` would fail because the runner checks that the `ProjectUser` is "Active". However, by this point, processing has already occurred on the cluster.

**Comment by jofeinstein** [comment]
So should we go ahead and complete R even if the ProjectUser isn't active? We could catch the an exception and write to the log.

**Comment by jofeinstein** [comment]
Actually, where is that check made? I don't see it in the runners or the views.

**Comment by matthew-li** [comment]
@jofeinstein Okay, I'm not able to recreate the error I _think_ I saw when completing the request on `develop`. I may also have confused it with the "Active" checking that occurs during the request for cluster access.

`R` gets processed just fine, which I suppose could be problematic, but let's not block #440 on this right now.
