### ISSUE TITLE
Replace hard-coded references to clusters

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#338]
Clusters are represented as `Resources` in the database, with names like "ABC Compute", "Lawrencium Compute", "Savio Compute", "Vector Compute", etc.

For the LRC instance of the application, create these objects for the various clusters.

In general, remove any hard-coded references to clusters (i.e., the "Cluster Name" filter on the Project List view).

**Comment by matthew-li** [comment]
@jofeinstein Can you update the filtering dropdown choices to use the cluster names extracted from the `Resource` object names, instead of a hard-coded list?

I'm not sure if there are many other instances of this. (The hard-coded display of projects by cluster can be left alone for now.)

**Comment by jofeinstein** [comment]
I only found the one instance in `project/forms.py` where `CLUSTER_NAME_CHOICES` was hardcoded. `get_project_compute_resource_name` in `allocation/utils.py` and `project/utils.py` has some hardcoded values but I don't think it makes sense to pull them from the database instead.

**Comment by matthew-li** [comment]
Agreed--I guess the main point of this issue can be to write the helper method to get a sorted list of cluster names from `Resources`, and then use that in `ProjectSearchForm`.

**Comment by jofeinstein** [comment]
I added `get_compute_resource_names` to `coldfront/core/utils/common.py`. It returns a sorted list of Resource names without ' Compute' in the name. Also use this function in the search form
