### ISSUE TITLE
Enhance Django admin interface

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#360]
The following should be possible in the Django admin interface:

- [x] Search for project name in "Allocation attributes", "Allocation user attributes", "Allocation attribute usages", and "Allocation user attribute usages".
- [x] Search for username in "Allocation user attributes" and "Allocation user attribute usages".
- [x] Search for project name in "Project Transactions" and "Project User Transactions".
- [x] Search for username in "Project User Transactions".
- [x] Link to or list `ProjectTransactions` from the single `Project` view.
- [x] Link to or list `ProjectUserTransactions` from the single `ProjectUser` view.

Consider what else would be useful to have, and add it to the above list.

- [x] Add users inline to groups admin page.
- [x] Add EmailAddress inline to users admin page.
- [x] List projects using project.name instead of project.title

**Comment by jofeinstein** [comment]
Is there a reason the verbose name for the ProjectUser model is "Project User Status". It confused me in the admin page.

**Comment by matthew-li** [comment]
Same here--I think it came like that out of the box.

The string is stored in the `Meta` class of the model itself, which I think requires a migration to be changed (not worth it IMO).

**Comment by jofeinstein** [comment]
I added inlines to the Group and User admin pages but am not sure where to put the code for them. Right now its in `core/utils/admin.py`. If you want to keep the inlines, where would you suggest putting it?

**Comment by matthew-li** [comment]
That seems like a reasonable place, given that `User` and `Group` aren't covered by any of our modules.

(`EmailAddress` is though, so maybe that should move.)

**Comment by matthew-li** [comment]
Go for it--the human-readable title came out of the box; while nice for users, we primarily care about the name on the backend.
