### ISSUE TITLE
Add a request "hub"

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#361]
Right now, users cannot easily see all of their ongoing/past requests. They need to navigate to each request-specific page to see requests of that type. Whereas staff and superusers have a "Requests" sub-menu in the Staff/Admin tabs, where they can see requests of all types.

It would be useful to have a view (linkable from the User Profile and the navbar) where users can see a summary of all of their pending/completed requests.
- It could be a flat page with different sections, one for each type (new project requests, renewal requests, cluster account requests, SU purchase requests, join requests, etc.)
- It could either:
    - List the requests directly, or
        - (Refactor and reuse existing list view code if going this route.)
    - Link to the associated list views, perhaps with a number showing how many pending and complete ones they have of that type.
- Wherever it is linked from, consider adding a red bubble indicating the number of pending requests they have (think of notifications).
    - This would also be useful for staff and admin.
- Staff/superusers might also benefit from the same page, but showing all requests in the system.

**Comment by jofeinstein** [comment]
@matthew-li, I can work on this if you want. I think I've mostly finished up the other tasks I had.

**Comment by matthew-li** [comment]
@jofeinstein Cool, thanks! You may want to start with a mock-up of the front end, so that everyone is on the same page, before you get too deep into it.
