### ISSUE TITLE
Enforce that LRC PIs are LBL employees

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#392]
On LRC, the set of users eligible to be Principal Investigators of projects is limited to LBL employees.

- [x] When requesting to create a new project:
    - If creating a new PI, enforce that the provided email address is an `@lbl.gov` address.
    - If selecting an existing PI, gray out PIs that do not have an associated `@lbl.gov` address.
- [x] Review the existing set of project PIs for any exceptions to this rule.

**Comment by jofeinstein** [comment]
There are 286 PIs and only 1 does not have an lbl email. 

Mark Labarge (username: mlabarge@coh.org). PI for pc_fresques001.
