### ISSUE TITLE
Restart Apache gracefully in Ansible

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#452]
Use `apachectl graceful` ([docs](https://httpd.apache.org/docs/2.4/stopping.html)) instead of restarting `httpd` entirely, to avoid dropping requests while updating web server configuration.

**Comment by Hzaakk** [comment]
In the service unit file for https (in `/usr/lib/systemd/system/httpd.service`), `apachectl graceful` is used with `ExecReload`. I think this means using `state: reloaded` in Ansible should use `apachectl graceful`. Currently, if `state: restarted` just stops and starts httpd (the docs say restart `bounces` the service, which could mean start and stop), it uses the `WINCH` kill-code (under `ExecStop` which apache docs indicate as a `graceful-stop`. I'll change the playbook to do `state: reloaded` in my Ansible PR (#436) 

![image](https://user-images.githubusercontent.com/43729496/185257010-3af088bd-f2fa-4f16-b34e-7f7ff0b0774c.png)
![image](https://user-images.githubusercontent.com/43729496/185256975-ba0da7c3-86b1-4063-9db1-c467d54467d9.png)

**Comment by Hzaakk** [comment]
Are there other services we could use `state: reloaded` with instead of `state: restarted`?

**Comment by matthew-li** [comment]
@Hzaakk Thanks for the detail--the main idea is to achieve this behavior described in the docs, so that we don't lose requests as we're updating the code:

> The USR1 or graceful signal causes the parent process to advise the children to exit after their current request (or to exit immediately if they're not serving anything). The parent re-reads its configuration files and re-opens its log files. As each child dies off the parent replaces it with a child from the new generation of the configuration, which begins serving new requests immediately.

No other services come to mind at the moment.
