### ISSUE TITLE
Add a view for pending project join requests

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#48]
Users should be able to view any pending requests they have to join existing projects.

**Comment by matthew-li** [comment]
Perhaps this and #38 could be placed under the User Profile, or in separate view(s) accessible from the User Profile. This is up for discussion.

**Comment by matthew-li** [comment]
From today's meeting, pending requests should be visible on the homepage.

**Comment by matthew-li** [comment]
@ViRu-ThE-ViRuS Sorry to change requirements under your feet again, but the workflow here is changing. There will be two types of pending requests (pending on staff vs. pending on project managers). See #74. Can you revisit this once I implement that (it'll probably be done by Monday)?

**Comment by ViRu-ThE-ViRuS** [comment]
@matthew-li sure!

**Comment by matthew-li** [comment]
@ViRu-ThE-ViRuS The blocker is out of the way now; thanks for waiting. As I mentioned in #74:

> Join requests that are waiting for the delay period to end should appear at the top of the Project Join List view.

This first request is a request to join the project, which needs to be approved by project managers (this could happen automatically after a delay period, or after a manager/PI approves it manually).

> Join requests that are waiting for staff approval should appear on the home page. It should be visible that they are pending on staff.

This second request is not really a join request; it's a request to have access to the project on the cluster. This request gets auto-generated after the join request is approved. We can re-use the existing Projects table on the home page; just add the `Pending` or `Active` badge to each row (see the Project Detail view for reference). It might also be helpful to add column headers ("Name", "Cluster Access").

Let me know if anything is unclear.
