### ISSUE TITLE
Break out BRC Condo project into a standalone cluster

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#496]
One of the Condo projects on BRC, `co_refmlab`, is starting its own standalone cluster.

- [x] Create a new standalone cluster, represented by a `Resource` (in `add_default_resources`).
- [x] Archive the existing project.
- [x] Add a management command to create a departmental/standalone project for the compute `Resource` with the given name. Use it to create the new project.
- [x] Perform potential additional steps.

**Comment by wfeinstein** [comment]
To be able to create  a standalone cluster on the portal, similar to a standard project, is needed.
