### ISSUE TITLE
Exclude inactive users as PI choices in new project requests

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#526]
In the form for selecting an existing PI during a new project request, hide users who are inactive (`is_active = False`).

Thus, disabling an old, no-longer-active user will prevent them from being selected as a PI (and being notified about it).

- [x] Update `SavioProjectExistingPIForm.exclude_pi_choices`.
- [x] Update `TestSavioProjectExistingPIForm`.

**Comment by matthew-li** [comment]
The testing part of this remains, so I'm leaving this open.

**Comment by Hzaakk** [comment]
I finished the testing in #493
