### ISSUE TITLE
Plan for getting Vector also added as a Resource to the ColdFront.

### ISSUE THREAD

**Issue by kmuriki** [ucb-rit/coldfront#60]

**Comment by kmuriki** [comment]
Note : A Vector user can be under a single Vector project at a given time. (Krishna to review this and confirm).

**Comment by matthew-li** [comment]
- There are no allocations, time limits, and renewals for Vector projects.
- There should be a way to request to create a new Vector project.
    - Joining one is already available.
- The constraint that users should only be part of one Vector project should be adhered to moving forward. Any existing violations should be fixed.

**Comment by matthew-li** [comment]
A new `Resource` named "Vector Compute" was/will be added in the `improve_workflow` branch. Assuming the data loading scripts will still be used, handling needs to be added to add allocations to this new `Resource` to "vector_*" projects.
