### ISSUE TITLE
Options to remove a user from a project

### ISSUE THREAD

**Issue by kmuriki** [ucb-rit/coldfront#62]
How can a user remove themselves from a project ?
Or How can an admin remove a user from a project ?

**Comment by matthew-li** [comment]
@kmuriki Currently, users cannot remove themselves from a project directly. A project manager can do so on their behalf. We can add a way for users to do this.

Staff can do this in the admin view: `/admin/project/project/{id}/change/`.

One point of consideration relating to allocation usage:
- We intend to display the project's total usage, as well as each user's individual usage under the project.
- If we remove a user mid-allocation-period, the individual usages displayed will no longer add up to the total, which may be confusing.

**Comment by matthew-li** [comment]
Removal requests should go into a pending queue, as there is backend processing that admins need to perform.

**Comment by matthew-li** [comment]
We should hide this button and view until then.

**Comment by matthew-li** [comment]
Some of the backend tasks admins would have to perform when a user is removed from a project include removal from UNIX groups and removal of Slurm associations.

Actual user accounts have not been deleted historically.

**Comment by matthew-li** [comment]
Set `ProjectUser.status` to `Removed` rather than deleting the `ProjectUser` object entirely. The corresponding `history` object can be used to determine when the user was removed, and by extension, in some circumstances, when the user's cluster account can be deactivated.

**Comment by matthew-li** [comment]
From today's meeting, rather than listing a sum of usages accrued by removed users, instead add a separate table listing these removed users and their usages.
