### ISSUE TITLE
Remove PI Request

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#72]
A user becomes a PI by being selected as one of the PIs when a project is being created (or when a project is selected to pool with).

At the moment, the `UserProfile.is_pi` field doesn't do much. We can remove the entry in the User Profile view, but leave the field there for now.

**Comment by matthew-li** [comment]
@kmuriki Note: if we allow any user to be selected as a PI, the admin performing the review will need to vet the requested PI (i.e., "Is this person actually a faculty member, etc.?").

**Comment by kmuriki** [comment]
Yes thats right. Most communication from the system will be to the PIs and/or managers.

**Comment by kmuriki** [comment]
Yes, project requests go into some pending queue I suppose and updating a person's record to PI role should still be in Admin's control.
