### ISSUE TITLE
Consider blocking access to most views until access agreement is signed

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#73]
We can prevent users from accessing certain views until they have signed the access agreement.

**Comment by matthew-li** [comment]
@kmuriki What do you think? For example, they can still access the "Join project" view manually, unless we prevent them.

**Comment by kmuriki** [comment]
Yes makes sense. Lets block access until user agreement is signed.

**Comment by ViRu-ThE-ViRuS** [comment]
@matthew-li lets discuss a list of views they can access even without signing the user agreement.

**Comment by matthew-li** [comment]
@ViRu-ThE-ViRuS At first glance, I'd say: home view, access agreement view, and user profile, but use your best judgment as well.

@kmuriki Do PIs who don't want cluster access need to sign the agreement to views their projects?

Staff and superusers don't need to sign it.

Also, let's gray out the navbar, except for the User menu (`templates.common.authorized_navbar.html`).

**Comment by kmuriki** [comment]
Hey very good point Matthew. User agreement is needed only for requesting account on the cluster. A PI who doesn't necessarily need a cluster account need not sign the user agreeement to manage their project. 

But if its just easier to enforce even such PIs also to review and sign the cluster user agreement may be we can just enforce it on them also. Its not something huge, just open the page, read text and click a button. We are not asking much from the PI.
