### ISSUE TITLE
Support a new cluster, "abc"

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#84]
There is only one project on this cluster, with the same name. There is no accounting involved, and we just need to support adding users to it.

**Comment by matthew-li** [comment]
For now, this cluster should be visible as a choice under the "Cluster Name" filter when attempting to join a project. It should not be added as a choice when creating a new project, since there is only one project.

The information for project `abc` should be copied from `fc_abc`.

**Comment by kmuriki** [comment]
Also should make the new ABC cluster shows up as the third cluster under the My BRC Projects section of the HOME page ? Or do you think the home page will become very busy ?

**Comment by matthew-li** [comment]
@kmuriki We could do that; I think it'd be best to put it under Savio/Vector, instead of making three columns.

We could also experiment with [tabs](https://getbootstrap.com/docs/3.3/components/#nav-tabs) (e.g., click on the Savio tab to show your Savio projects, the Vector tab to show your Vector projects, etc.). That might make things cleaner.

**Comment by matthew-li** [comment]
This support has been added in #96. Some setup commands need to be run; these are available in the PR.

@kmuriki I've added a new section under Savio/Vector for now--we can redesign that as needed.

**Comment by kmuriki** [comment]
Looks great! Maybe move we can place ABC under Vector instead of under Savio. But its a minor thing. Thanks.

**Comment by matthew-li** [comment]
Sure, it's updated now.
