### ISSUE TITLE
Test sync_brcdb script using ColdFront API endpoints

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#85]
This script was developed to interact with the previous project's API endpoints. It appears that it only uses the `Job` endpoints, which have not changed, so the script should work as before.

**Comment by ViRu-ThE-ViRuS** [comment]
fix: https://github.com/ucb-rit/slurm-banking-utilities/pull/1

**Comment by matthew-li** [comment]
This should not be run until:
1. #232 is resolved. Currently, usages are updated even if the job is outside of the current allocation range. Running this script would lead to inconsistencies.
2. The script is made more memory-efficient. Currently, all jobs are loaded into memory (requiring multiple gigabytes) before being sent to the myBRC REST API. This leads to crashes.

**Comment by ViRu-ThE-ViRuS** [comment]
https://github.com/ucb-rit/slurm-banking-utilities

**Comment by ViRu-ThE-ViRuS** [comment]
these issues have been fixed
