### ISSUE TITLE
Allow admins to download survey responses in bulk

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#88]
Admins should be able to download survey responses, both for individual projects and for all projects returned by some query (e.g., created in some date range, etc.).

The format (JSON, CSV, etc.) are up for discussion.

**Comment by matthew-li** [comment]
Implement a management command that can be run on the server (`coldfront.core.project.management.commands.get_survey_responses`).
- Results should be written to `stdout`. If errors occur, they should be written to `stderr`.
    - (The calling user may always redirect to a file themselves.)
- It should have a _required_ `format` parameter, which can be either `csv` or `json`.
- It should have an _optional_ `--allowance_type` parameter, which allows the user to specify one of the following values: `['ac_', 'co_', 'fc_', 'ic_', 'pc_']`. The results should include only responses for `Projects` having the specified prefix in their names.
- Date filtering is not needed at this time.
- Write unit tests to ensure that the results are as expected and that the written output can be parsed as a valid JSON or CSV.
    - These tests can be added to a class named `coldfront.core.project.tests.test_commands.test_get_survey_responses.TestGetSurveyResponses`.

**Notes**
- Survey responses are stored in a `JSONField` named `survey_answers` in the `SavioProjectAllocationRequest` model.
- Factor out the core logic so that JSONs and CSVs may be generated from the front-end as well (to be incorporated into a future view of some kind, to be determined).
    - In particular, functions that generate the JSON string and CSV string could then be used both (a) from the management command and (b) from the front-end, sent directly in an HTTP response as a file download.
- The ability to download these from the front-end is not needed at this time; it will likely be incorporated as part of #167.
- For examples of management command parameters, search for `def add_arguments`.
    - Also, refer to the Django [documentation](https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/).
- In unit tests, use the `django.core.management.call_command` method to invoke the command. Below is some sample code that invokes the command and retrieves the `stdout` and `stderr`:
    ```
    from django.core.management import call_command
    from io import StringIO

    out, err = StringIO(), StringIO()
    args = ['get_survey_responses', 'json', '--allowance_type', 'fc_']
    kwargs = {'stdout': out, 'stderr': err}
    call_command(*args, **kwargs)
    output, error = out.getvalue(), error.getvalue()
    ```

**Comment by ViRu-ThE-ViRuS** [comment]
closing here now
